// blog/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div id="header"></div>
    <div>Name: blog</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
</template>

<script setup>
import { onMounted } from 'vue';
import React from 'react';
import ReactDOM from 'react-dom';
import Header from 'host/Header';

onMounted(() => {
  ReactDOM.render(React.createElement(Header), document.getElementById('header'));
});
</script>

// host/src/App.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import HomeContent from './HomeContent';
import Header from './Header';
import Footer from './Footer';
import appOne from 'appOne/App';
import './index.scss';
const container = (document.createElement = appOne);
const App = () => (
  <div className='mt-10 text-3xl mx-auto max-w-6xl'>
    <Header />
    <div className='bg-red-400'>
      <div id='test'></div>
      <HomeContent />
    </div>
    <Footer />
  </div>
);
ReactDOM.render(<App />, document.getElementById('app'));
